name: Update OpenClash Rules

on:
  schedule:
    # 定时任务，这里以每天凌晨0点为例
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发
    inputs:
      reason:
        description: 'Reason for manual dispatch'
        required: false
        default: 'Manual update'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Fetch Updates for ai.yaml
      run: |
        curl -o rules/ai.yaml https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.yaml

    - name: Fetch Updates for apple-cn.yaml
      run: |
        curl -o rules/apple-cn.yaml https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/apple-cn.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add scripts/rules/ai.yaml
        git commit -m 'Update ai.yaml'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
