name: Update OpenClash Rules

on:
  schedule:
    # 定时任务，这里以每天凌晨0点为例
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发
    inputs:
      reason:
        description: 'Reason for manual dispatch'
        required: false
        default: 'Manual update'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create 'rules' directory if it doesn't exist
      run: |
        mkdir -p rules
        echo "Created 'rules' directory."

    - name: Fetch Updates for Rules
      run: |
        declare -A files
        files["networktest.yaml"]="https://raw.githubusercontent.com/DustinWin/ruleset_geodata/refs/heads/mihomo-ruleset/networktest.yaml"

        for file in "${!files[@]}"; do
          curl -L -o "rules/$file" "${files[$file]}"

          if [[ -s "rules/$file" ]]; then
            if [[ "$file" == *.yaml ]]; then
              sed -i "1i#!name = ${file%.yaml}" "rules/$file"
              sed -i "2i#!date = $(date +'%Y-%m-%d %H:%M:%S')" "rules/$file"
              sed -i "3i#!" "rules/$file"
            fi
          else
            echo "Failed to download ${file}. Keeping the existing version."
            rm -f "rules/$file"  # 删除下载失败的文件
          fi
        done
        
    - name: Modify networktest.yaml
      run: |
        sed -e 's/- DOMAIN-SUFFIX,/ - +./g' \
            -e '/- DOMAIN,www.speedtest.net.cdn.cloudflare.net/d' \
            -e 's/- DOMAIN-KEYWORD,ipv6-test/ - test-ipv6.com/g' \
            -e '/- DOMAIN-KEYWORD,speedtest/d' \
            -e '/- DOMAIN-KEYWORD,testipv6/d' \
            -e 's/- DOMAIN-KEYWORD,test-ipv6/ - test-ipv6.com/g' \
            -i rules/networktest.yaml
        echo "Modified networktest.yaml"

    - name: Download proxy_host to proxy-classical.list
      run: |
        curl -s -o rules/proxy-classical.list https://raw.githubusercontent.com/qoli/SyncnextClash/main/passwall/proxy_host
        echo "Downloaded proxy_host to rules/proxy-classical.list"
        if [[ -s rules/proxy-classical.list ]]; then
          echo "Successfully downloaded proxy_host to proxy-classical.list"
        else
          echo "Failed to download proxy_host."
          exit 1
        fi

    - name: Download direct_host to unbreak-classical.list
      run: |
        curl -s -o rules/unbreak-classical.list https://raw.githubusercontent.com/qoli/SyncnextClash/main/passwall/direct_host
        echo "Downloaded direct_host to rules/unbreak-classical.list"
        if [[ -s rules/unbreak-classical.list ]]; then
          echo "Successfully downloaded direct_host to unbreak-classical.list"
        else
          echo "Failed to download direct_host."
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add rules/*
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m 'Update Rules files'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
